// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nagzxvpuoagsbrfwgogv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZ3p4dnB1b2Fnc2JyZndnb2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjQ1NTIsImV4cCI6MjA2NjU0MDU1Mn0.zvMxU8Pu4k7z3ikrdCAP_2Fp1I5A12iFZ9pyi5tN8oA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});